---

- name: Disable networking
  systemd:
    name: networking
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Enable systemd-resolved
  systemd:
    name: systemd-resolved
    state: started
    enabled: yes
    
- name: Create resolv.conf symlink
  file:
    src: /lib/systemd/resolv.conf
    dest: /etc/resolv.conf
    force: yes
    state: link
    
- name: Create network file for dhcp
  template:
    src: dhcp.network
    dest: /etc/systemd/network/dhcp.network
  register: networkd

- name: Enable systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: yes

- name: Restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
  when: networkd.changed
  register: networkrestarted

- name: Wait for network online
  command: /lib/systemd/systemd-networkd-wait-online
  when: networkrestarted.changed

- name: Remove ifupdown
  apt:
    name: ifupdown
    state: absent
    autoremove: yes
    purge: yes

- name: Remove DHCP client
  apt:
    name: isc-dhcp-client
    state: absent
    autoremove: yes
    purge: yes
