---

- name: Base settings Debian 10 after minimal installation.
  hosts: 127.0.0.1
  connection: local
  roles:
    - grub
    - systemd-networkd
    - bash
    - sshd
    - remove-unwanted-packages
    - vim
    - printip
    - install-basic-packages
