---
- name: Base settings of minimal installation of Debian 10
  hosts: 127.0.0.1
  connection: local

  handlers:
    - name: restart-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    - name: restart-resolved
      systemd:
        name: systemd-resolved
        state: restarted

    - name: update-grub
      command: /usr/sbin/update-grub

  tasks:

    - name: Remove GRUBs timeout
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: 'GRUB_TIMEOUT=0'
      notify: update-grub
    
    - name: Remove quiet from kernel parameters
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
      notify: update-grub
    
    - name: Call handlers
      meta: flush_handlers

    - name: Configure SSH Daemon
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
        validate: /usr/sbin/sshd -t -f %s
    - name: Disable ssh.service
      systemd:
        name: ssh.service
        state: stopped
        enabled: no
    - name: Enable ssh.socket
      systemd:
        name: ssh.socket
        state: started
        enabled: yes

    - name: Remove ifupdown
      apt:
        name: ifupdown
        state: absent
        autoremove: yes
        purge: yes
    - name: Remove DHCP client
      apt:
        name: isc-dhcp-client
        state: absent
        autoremove: yes
        purge: yes
    - name: Remove wpasupplicant
      apt:
        name: wpasupplicant
        state: absent
        autoremove: yes
        purge: yes
    - name: Remove bluez
      apt:
        name: bluez
        state: absent
        autoremove: yes
        purge: yes
    - name: Remove apparmor
      apt:
        name: apparmor
        state: absent
        autoremove: yes
        purge: yes
    - name: Remove rsyslog
      apt:
        name: rsyslog
        state: absent
        autoremove: yes
        purge: yes
      
    - name: Disable networking
      systemd:
        name: networking
        state: stopped
        enabled: no
      ignore_errors: yes
    - name: Enable systemd-resolved
      systemd:
        name: systemd-resolved
        state: started
        enabled: yes
    - name: Create resolv.conf symlink
      file:
        src: /lib/systemd/resolv.conf
        dest: /etc/resolv.conf
        force: yes
        state: link
    - name: Create network file for dhcp
      template:
        src: dhcp.network
        dest: /etc/systemd/network/dhcp.network
      register: networkd

    - name: Enable systemd-networkd
      systemd:
        name: systemd-networkd
        state: started
        enabled: yes
    
    - name: Restart systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted
      when: networkd.changed
      register: networkrestarted

    - name: Wait for network online
      command: /lib/systemd/systemd-networkd-wait-online
      when: networkrestarted.changed

    - name: Install mc
      apt:
        name: mc
        state: latest
    - name: Install ViM
      apt:
        name: vim
        state: latest
    - name: Configure ViM
      lineinfile:
        path: /etc/vim/vimrc
        regexp: '^set bg='
        line: 'set bg=dark'
    - name: Install man
      apt:
        name: man
        state: latest
    - name: Install bash-completion
      apt:
        name: bash-completion
        state: latest

    - name: Create printIP.service unit file
      template:
        src: printIP.service
        dest: /etc/systemd/system/printIP.service
    - name: Reload systemd
      systemd:
        daemon-reload: yes
    - name: Enable printIP.service
      systemd:
        name: printIP.service
        enabled: yes
    - name: Disable tty1
      systemd:
        name: getty@tty1.service
        enabled: no
        masked: yes
    - name: Reboot
      debug:
        msg: Now reboot the system.
        

