---

- name: Install ViM
  apt:
    name: vim
    state: latest

- name: Configure ViM
  lineinfile:
    path: /etc/vim/vimrc
    regexp: '^set bg='
    line: 'set bg=dark'

- name: Set ViM as default system wide editor
  shell: update-alternatives --set editor /usr/bin/vim.basic
