---

- name: Remove GRUBs timeout
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=0'
  notify: update-grub

- name: Remove quiet from kernel parameters
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
  notify: update-grub

- name: Call handlers
  meta: flush_handlers
    